name: Build package
if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
jobs:
  Build-package:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -r requirements.txt
      - run: make package
