name: Build package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  Build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: make package
